USE yareli3_project;

CREATE TABLE USER_TYPES(
    ID_T INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(150) NOT NULL
);
CREATE TABLE USERS(
    ID_U INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Mail VARCHAR(150) NOT NULL,
    Name VARCHAR(150) NOT NULL,
    LastName VARCHAR(150) NOT NULL,
    Date DATE NOT NULL,
    Type INT NOT NULL,
    FOREIGN KEY (Type) REFERENCES USER_TYPES(ID_T)
);

CREATE TABLE PROJECTS(
    ID_P INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(150) NOT NULL,
    Description VARCHAR(500) NOT NULL,
    Image VARCHAR(300) NOT NULL,
    Creation DATE NOT NULL,
    Adviser INT NOT  NULL,
    FOREIGN KEY (Adviser) REFERENCES USERS(ID_U)
);

CREATE TABLE PIVOT(
    ID_PIV INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_U INT NOT NULL,
    ID_P INT NOT NULL,
    FOREIGN KEY (ID_U) REFERENCES USERS(ID_U),
    FOREIGN KEY (ID_P) REFERENCES PROJECTS(ID_P)
);
